seed = 12345
step_duration = 20
drag = 0.0
stddev = 0.2
allow_noop = false

[ball]
    starts = [[0.2, 0.2], [0.2, 0.9]] # List of possible starting points.
    radius = 0.02

[target]
    location = [0.2, 0.9]
    radius = 0.04
    
# Board boundary
[[obstacles]]
    points = [[0.0, 0.0], [0.0, 0.06], [1.0, 0.06], [1.0, 0.0]]
[[obstacles]]
    points = [[0.0, 0.44], [0.0, 0.5], [1.0, 0.5], [1.0, 0.44]]
[[obstacles]]
    points = [[0.0, 0.0], [0.0, 0.5], [0.06, 0.5], [0.06, 0.0]]
[[obstacles]]
    points = [[1.0, 0.0], [1.0, 0.5], [0.94, 0.5], [0.94, 0.0]]